// Generated by CoffeeScript 1.4.0
(function() {
  var myFeature;

  myFeature = {
    config: {
      wrapper: '#myFeature',
      container: 'div',
      urlBase: 'foo.php?item='
    },
    init: function(config) {
      $.extend(myFeature.config, config);
      return $(myFeature.config.wrapper).find('li').each(function() {
        return myFeature.getContent($(this));
      }).click(function() {
        return myFeature.showContent($(this));
      });
    },
    buildUrl: function($li) {
      return myFeature.config.urlBase + $li.attr('id');
    },
    getContent: function($li) {
      var url;
      $li.append(myFeature.config.container);
      url = myFeature.buildUrl($li);
      return li.find(myFeature.config.container).load(url);
    },
    showContent: function($li) {
      $li.find('div').show();
      return $myFeature.hideContent($li.siblings());
    },
    hideContent: function($element) {
      return $element.find('div').hide();
    }
  };

  $(document).ready(function() {
    return myFeature.init();
  });

}).call(this);
