// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    return $('#myFeature li').append("<div/>").each(function() {
      return $(this).find("div").load('foo.php?item=' + $(this).attr('id'));
    }).click(function() {
      $(this).find('div').show();
      return $(this).siblings().find('div').hide();
    });
  });

}).call(this);
